export const USER_TYPE_CUSTOMER = 1
export const USER_TYPE_FREELANCER = 2
export const USER_TYPE_RECRUITER = 3
export const USER_TYPE_JOB_SEEKER = 4

export const USER_TYPE_CUSTOMER_PERSON = 1
export const USER_TYPE_CUSTOMER_COMPANY = 2